version: "3"

services:
  nextjs:
    build: .
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - our-net
    volumes:
      - shared-volume:/usr/src/app

  mysql:
    image: mysql:8.3.0
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
    ports:
      - "3306:3306"
    networks:
      - our-net
    volumes:
      - shared-volume:/usr/src/app

volumes:
  shared-volume:
networks:
  our-net:
    external: true
